name = "Quilt Mod"
description = "A template for QuiltMC Minecraft mods"

[[inputs]]
id = "mod_name"
type = "string"

prompt = "What is the name of your mod?"

[[inputs]]
id = "mod_id"
type = "string"

prompt = "What is the ID of your mod?"

[[inputs]]
id = "mod_description"
type = "string"

prompt = "What is the description of your mod?"

[[inputs]]
id = "main_class_name"
type = "string"

prompt = "What is the name of your main class?"

[[inputs]]
id = "mod_source"
type = "string"

prompt = "What is the repository URL of your mod?"

[[inputs]]
id = "use_github_ci"
type = "bool"

prompt = "Setup GitHub Actions for CI?"

[[inputs]]
id = "initialize_git"
type = "bool"

prompt = "Initialize Git repository?"

[[files]]
path = ".github"
only_if = "use_github_ci"

[[files]]
path = ".gitignore"
only_if = "initialize_git"

[[after]]
command = "git init"
only_if = "initialize_git"
